<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>ImageOptimizer</AssemblyName>
    <Version>1.0.0</Version>
    <Company>Jamo</Company>
    <Product>Bildoptimerare för webben</Product>
    <Description>Komprimerar bilder för uppladdning till webshop</Description>
  </PropertyGroup>

</Project>
